version: '3.7'


services:


    postgres:
          image: postgres:latest
          container_name: my_postgres
          environment :
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
          ports: 
            - 5432:5432 #postgresQL 포트번호임